### PR TITLE
Add top prospects feature

### PR DESCRIPTION
**Pull request by TylerLiu42**
This PR does two things: 
1. Adds missing import statements for the changes in https://github.com/schorrm/pybaseball/pull/2. My apologies for the error, 
2. Introduces a feature for a listing of top prospects by team or leaguewide.

I will update this PR to include the docs once I get the green light from you

Capture

### CODE REVIEW

**Comment by TylerLiu42** [comment]
Side note: would it make sense to turn this repo into a standalone repository? It seems like you have taken the initiative to start this up again, and the original author has been inactive for nearly a year. 

Noone's contributions are being counted by GitHub right now since we are working on a forked repo.

**Comment by schorrm** [comment]
Well done!
So I already added the `statcast_batter_exitvelo_barrels` to the `__init__.py`, so no need (please pull and undo that maybe?)
This is a good PR, undo the import and I'll merge.
Happy to move to a standalone repo, should I make an issue for that? Name?
We'll want a new package name anyway for PyPI

**Comment by TylerLiu42** [comment]
Removed import and updated doc. To move to a standalone repo, contact GitHub support. https://support.github.com/contact
Source: https://help.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork

Not sure what would be a good name, BaseballSaber for "sabermetrics"? 

Also, do you have an email that I can contact you with?

**Comment by schorrm** [comment]
Yeah, my gmail handle is mosheraphael.
Looks good. I'll merge.

**Pull request merged**
