### PR TITLE
Updating README and setup for publishing on PyPI

### PR DESCRIPTION
**Pull request by schorrm**
Updated the documentation and the setup.py ahead of publication on PyPI.
- Version is now 2.0.0
- Publication will be under pybaseball2
- all links in README now point to this repo
- Delete README.rst in favor of just the MD
- Python version is now only 3.6+

### CODE REVIEW

**Comment by schorrm** [comment]
@andersonfrailey , @TylerLiu42 , @TAThor 
Care to weigh in?

**Comment by andersonfrailey** [comment]
@schorrm this looks great! Thanks for taking care of it.

**Comment by schorrm** [comment]
Great. Merging, and it'll go up on PyPI soon

**Comment by schorrm** [comment]
We're on PyPI and I set up the CI to upload to PyPI on every new release

**Pull request merged**
