### PR TITLE
Add plotting functions

### PR DESCRIPTION
**Pull request by andersonfrailey**
I stumbled on the MLBAM stadium coordinates in [this repo](https://github.com/bdilday/GeomMLBStadiums) and wrote a couple functions for plotting. I used altair, but I'd be happy to switch to matplotlib or bokeh if that's preferable.

The first, `plot_stadium`, just returns a plot with the stadium outline. `spraychart` makes a spraychart using statcast data. Example:
spraychart

### CODE REVIEW

**Comment by schorrm** [comment]
This is really nice! Is it possible to handle the aspect ratio here differently?

**Comment by schorrm** [comment]
Added `include_package_data=True` to setup.py, so it'll actually install the CSV file.

**Comment by schorrm** [comment]
I don't see any reason why not Altair, at least right now. Can we get that plot to be not squishy? And another maybe convenience mechanism -- can we make a simple flag to color by result?

**Comment by andersonfrailey** [comment]
Yeah I've been working on the aspect ratio. Just need to play with the width and height of the plot. Gonna push some changes up soon.

> can we make a simple flag to color by result?

As in like single, double, out, etc., right? Yep, there is. I'll include that in the changes.

**Comment by schorrm** [comment]
Also -- not pinning this on you in any way, but more making a note to self -- since we have this (and statcast data) -- we should make a similar thing for pitch location charts

**Comment by andersonfrailey** [comment]
Here's the new look
spraychart

>we should make a similar thing for pitch location charts

Agreed here. A lot of great features we could add.

**Comment by schorrm** [comment]
I think I found an improvement for aspect ratio
image

**Comment by schorrm** [comment]
I think it's better with this -- feel free to rollback the commit if you disagree

**Comment by schorrm** [comment]
@andersonfrailey ? What do you think?

**Comment by andersonfrailey** [comment]
Your change looks good to me! Any other feature/functionality you want me to add on?

**Comment by schorrm** [comment]
I think we're good in here -- I definitely want to use this as the basis for some more stuff that's related, like pitcher sprays, but that'll come separately I assume.
Oh, and if you have a new name suggestion, it may be worthwhile if we want to put the fork up on the PyPI.

**Comment by schorrm** [comment]
Oh, actually maybe one thing -- can we parametrize what the color is? I think outcome is the correct one for the default, but if, say, I wanted to plot Altuve's vs someone else's (assuming I concatted the DFs with their IDs / names etc). Maybe have that line in there creating the `label` column unconditionally (cheap enough, no need to add an if check), but just have `color_by='label', legend='Outcome'` in the parameters?

**Comment by schorrm** [comment]
This is already loads of fun
image

**Comment by andersonfrailey** [comment]
Latest batch of commits added the ability to color by player and I added a subtitle to say which ballpark you're plotting on. Here's the new looks
multiplayer_spraychart
spraychart

I need to make a couple of tweaks to the subtile on the generic field. Will push those shortly.

**Comment by andersonfrailey** [comment]
Fixes are up. 
generic

**Comment by schorrm** [comment]
I liked it better with CIN but sure. And if someone really needs a generic stadium, there's always Kauffman.
Great job, Imma merge.
And a side note: for now I'm leaving the CSV where it is. If we start having other data files come with this thing, we'll move them to a separate folder.

**Pull request merged**
